-- One-time metadata-only cutover for the verified secretary_db deployment.
-- This is NOT a Goose migration. Do not use on a fresh/unverified database.
-- Execute the entire file in one transaction, after schema comparison and approval.
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';
DO $$
BEGIN
  IF current_database() <> 'secretary_db' THEN
    RAISE EXCEPTION 'This cutover was prepared for secretary_db only';
  END IF;
  IF to_regclass('public.goose_db_version') IS NOT NULL THEN
    RAISE EXCEPTION 'Goose metadata already exists; inspect status rather than re-baselining';
  END IF;
  IF to_regclass('public.atlas_schema_revisions') IS NULL THEN
    RAISE EXCEPTION 'Expected verified Atlas deployment';
  END IF;
  LOCK TABLE public.atlas_schema_revisions IN ACCESS EXCLUSIVE MODE;
  IF EXISTS (SELECT 1 FROM public.atlas_schema_revisions WHERE applied <> total OR COALESCE(error, '') <> '')
    OR NOT EXISTS (SELECT 1 FROM public.atlas_schema_revisions WHERE version = '20260924100000' AND applied = 8 AND total = 8)
    OR EXISTS (SELECT 1 FROM public.atlas_schema_revisions WHERE version::bigint > 20260924100000) THEN
    RAISE EXCEPTION 'Atlas state changed or is incomplete; recheck the baseline';
  END IF;

  -- Matches the PostgreSQL ledger definition in Goose v3.27.0.
  CREATE TABLE public.goose_db_version (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp NOT NULL DEFAULT now()
  );
  INSERT INTO public.goose_db_version (version_id, is_applied)
    VALUES (0, true), (20260928000000, true);
  DROP TABLE public.atlas_schema_revisions;
END $$;
